### ISSUE TITLE
Allow configuring host/port

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/netviel#1]

**Comment by agenbite** [comment]
Hi! What a wonderful addition this is to my email setup! Thanks for writing it!

I have a question, though. If I wanted to access to netviel from a different machine (I know, I know, but it'll be inside a private vpn), how would I configure it? I've read the commit that closed this issue, but I can't figure it out. Thanks in advance!

**Comment by agenbite** [comment]
I got it running by modifying the code at __main.py__ and replacing the last line by `app.run(port=args.port, host='0.0.0.0')` and then following [the instructions](https://github.com/DavidMStraub/netviel/blob/master/docs/developers.md) to build it from code.
