### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by steffenfritz** [DavidMStraub/netviel#12]
It would help a lot for the use and further development of netviel, if there would be an open source license.

I will send a pull request with a suggestion.

**Comment by DavidMStraub** [comment]
Oops, how could I forget that ... thanks for the PR but I'd prefer MIT.

**Comment by steffenfritz** [comment]
MIT is ok :)

**Comment by DavidMStraub** [comment]
Fixed by 999f87abd7179f7083e9575f4699f1ea9b2351aa.
