### ISSUE TITLE
Fix attachment download

### ISSUE THREAD

**Issue by edkedk99** [DavidMStraub/netviel#19]
Hello,

It seems there is a small error in the following line, and I thought it was easier for the mantainer to just be informed rather than a pull request.

The send_file function in Flask changed its keyword parameter name: "attachment_filename" keyword argument, should be now "download_name" in the mentioned line 

https://github.com/DavidMStraub/netviel/blob/ad9eb0cd36c4102782fee9c5c3d418414d9b24c2/netviel/api.py#L124

And thank you for this app, it is very useful.

**Comment by DavidMStraub** [comment]
Thanks, you're right, I would appreciate a pull request. It will also require setting a minimum flask version in setup.py.
