### ISSUE TITLE
netviel is not reachable from other networks

### ISSUE THREAD

**Issue by baba2k** [DavidMStraub/netviel#22]
Hi David, 

is it possible to make netviel reachable from other networks with the flask host=0.0.0.0 parameter? I want to start netviel in a docker container and reach it through several VLANs.

Thanks :-)

Best, baba

**Comment by DavidMStraub** [comment]
Hi,

do you want to user the flask dev server, and if so, why? I personally use `gunicorn -b 0.0.0.0:$PORT netviel.wsgi:app`.

**Comment by baba2k** [comment]
I'm started netviel with 'pyhton3 -m netviel' as descriped in README.I am not familar with flask/gunicorn. Can i use your command to start netviel?

Thanks!

**Comment by baba2k** [comment]
Hi @DavidMStraub,

`FROM python:3-alpine
RUN apk add git notmuch 
RUN pip install notmuch netviel
RUN echo "*/15 * * * * notmuch new" >> /var/spool/cron/crontabs/root
CMD notmuch new && crond && python3 -m netviel`

Can you help me with starting gunicorn when installing netviel with pip?

Thank you!
